name: kado_ceria
description: "kado ceria"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  page_flip: ^0.2.5+1
  just_audio: ^0.10.4
  provider: ^6.0.5
  cloud_firestore: ^5.6.12
  firebase_core: ^3.15.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/kadoceria.png"
  min_sdk_android: 21
  min_sdk_ios: 11.0
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo/kadoceria.png"
  adaptive_icon_mask: true

flutter:
  uses-material-design: true
  assets:
    - assets/dongeng_janiti/halaman/
    - assets/dongeng_janiti/audio_narasi_indonesia/
    - assets/dongeng_janiti/audio_narasi_sunda/
    - assets/dongeng_janiti/audio_objek/
    - assets/dongeng_janiti/audio_backsound/
    - assets/sakeclak_cihujan_hayang_ka_sagara/halaman/
    - assets/sakeclak_cihujan_hayang_ka_sagara/audio_narasi_indonesia/
    - assets/sakeclak_cihujan_hayang_ka_sagara/audio_narasi_sunda/
    - assets/sakeclak_cihujan_hayang_ka_sagara/audio_objek/
    - assets/sakeclak_cihujan_hayang_ka_sagara/audio_backsound/
    - assets/metadata.json
    - assets/logo/
    - assets/
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
